HTTP_OK 				 = 200
HTTP_NO_CONTENT          = 204
HTTP_BAD_REQUEST 		 = 400
HTTP_UNAUTHORIZED 		 = 401
HTTP_FORBIDDEN 			 = 403
HTTP_NOT_FOUND 			 = 404
HTTP_NOT_ACCEPTABLE 	 = 406
HTTP_PRECONDITION_FAILED = 412
HTTP_EXPECTATION_FAILED  = 417
HTTP_LOCKED 			 = 423
HTTP_NOT_IMPLEMENTED 	 = 501

REQUEST_SIGN_UP	= 1
REQUEST_LOGIN	= 2
INFORM_FILE_CHANGE = 200

TARGET_FILE_CREATORS    = 2
TARGET_FILE_ROLES       = 3
TARGET_FILE_DATES       = 4